10paradoteo
OompaLoompas/images pull request #25
Opened 2022-05-29 16:15 UTC by P2019SARAKATSANIS

10 paradoteo images

2022-05-30 00:20 UTC, u2nmd requested changes
Κάποιες από τις εικόνες είναι κάπως μικρές και φοβάμαι ότι δεν θα φαίνονται καλά τόσο στην βιογραφία όσο και στην μελέτη περίπτωσης. Δώσε μας ένα ντέμο λινκ για να δούμε πως φαίνονται στο site.

2022-05-30 20:52 UTC, u2nmd commented
> Κάποιες από τις εικόνες είναι κάπως μικρές και φοβάμαι ότι δεν θα φαίνονται καλά τόσο στην βιογραφία όσο και στην μελέτη περίπτωσης. Δώσε μας ένα ντέμο λινκ για να δούμε πως φαίνονται στο site.

Συνεχίζουν κάποιες εικόνες να είναι σχετικά μικρές (όχι τα thumbnails). @p19pasc εσύ τι λες;

2022-05-30 22:14 UTC, p19pasc approved these changes
Θεωρώ πως δεν χρειάζεται τόση μεγάλη έφμαση στο μέγεθος, αλλά χωρίς ένα ντέμο δεν μπορούμε να έχουμε ακριβής εικόνα. Κατά τα άλλα δεν υπάρχει κάποιο θέμα στην αποδοχή του PR.

2022-06-01 21:55 UTC, u2nmd approved these changes

2023-02-18 00:10 UTC, closed without merging